#!/bin/bash
#comment
#count=16
g++ -fopenmp main.cpp -o main
./main >> output_locks.txt
#echo $count
#for i in $(seq $count); do
 #   echo $i
  #  export OMP_NUM_THREADS=$i
   # ./main >> output6.txt
#done
